const fs = require('fs');
let c = fs.readFileSync('public/index.html', 'utf8');

const mappings = {
    'matrixheader': 'matrix-header',
    'matrixbody': 'matrix-body',
    'searchmatris': 'search-matris',
    'raporaytable': 'rapor-ay-table',
    'raporlistetable': 'rapor-liste-table',
    'raporogrencitable': 'rapor-ogrenci-table',
    'raporayfooter': 'rapor-ay-footer',
    'raporlistefooter': 'rapor-liste-footer',
    'raporogrencifooter': 'rapor-ogrenci-footer',
    'rapormonthfilter': 'rapor-month-filter',
    'raporsearch': 'rapor-search',
    'newogrenci': 'new-ogrenci',
    'neway': 'new-ay',
    'newtur': 'new-tur',
    'newtarih': 'new-tarih',
    'newdekont': 'new-dekont',
    'newtutar': 'new-tutar',
    'newnotlar': 'new-notlar',
    'settingsname': 'settings-name',
    'settingslogo': 'settings-logo',
    'settingslogopreview': 'settings-logo-preview',
    'studenttable': 'student-table',
    'addstudentmodal': 'add-student-modal',
    'addpaymentmodal': 'add-payment-modal',
    'editstudentmodal': 'edit-student-modal',
    'editpaymentmodal': 'edit-payment-modal',
    'siblingpagecontainer': 'sibling-page-container',
    'modetoggle': 'mode-toggle',
    'expenselistbody': 'expense-list-body',
    'expensetotalamount': 'expense-total-amount',
    'expensemonthfilter': 'expense-month-filter',
    'expensesearch': 'expense-search',
    'expensecatfilter': 'expense-cat-filter',
    'expensesort': 'expense-sort',
    'addexpensemodal': 'add-expense-modal',
    'editexpensemodal': 'edit-expense-modal',
    'hardresetpassword': 'hard-reset-password',
    'deletemonthselect': 'delete-month-select',
    'dangermodaltext': 'danger-modal-text',
    'dangerconfirmbtn': 'danger-confirm-btn',
    'dangermodal': 'danger-modal',
    'editexpenseid': 'edit-expense-id',
    'editexpenseay': 'edit-expense-ay',
    'editexpensetutar': 'edit-expense-tutar',
    'editexpensekategori': 'edit-expense-kategori',
    'editexpenseaciklama': 'edit-expense-aciklama',
    'editexpensedekont': 'edit-expense-dekont',
    'editexpensetarih': 'edit-expense-tarih',
    'expenseay': 'expense-ay',
    'expensetarih': 'expense-tarih',
    'expensetutar': 'expense-tutar',
    'expensekategori': 'expense-kategori',
    'expenseaciklama': 'expense-aciklama',
    'expensedekont': 'expense-dekont',
    'nssira': 'ns-sira',
    'nstc': 'ns-tc',
    'nsad': 'ns-ad',
    'nssoyad': 'ns-soyad',
    'nsanne': 'ns-anne',
    'nsbaba': 'ns-baba',
    'nsegitim': 'ns-egitim',
    'nsgiris': 'ns-giris',
    'nscikis': 'ns-cikis',
    'editoldtc': 'edit-old-tc',
    'edittc': 'edit-tc',
    'editsira': 'edit-sira',
    'editno': 'edit-no',
    'editsinif': 'edit-sinif',
    'editad': 'edit-ad',
    'editsoyad': 'edit-soyad',
    'editanne': 'edit-anne',
    'editbaba': 'edit-baba',
    'editegitim': 'edit-egitim',
    'editgiris': 'edit-giris',
    'editcikis': 'edit-cikis',
    'editpaymentogrenci': 'edit-payment-ogrenci',
    'editpaymentid': 'edit-payment-id',
    'editpaymentay': 'edit-payment-ay',
    'editpaymenttur': 'edit-payment-tur',
    'editpaymenttarih': 'edit-payment-tarih',
    'editpaymentdekont': 'edit-payment-dekont',
    'editpaymenttutar': 'edit-payment-tutar',
    'editpaymentnotlar': 'edit-payment-notlar',
    'paymentfields': 'payment-fields',
    'studentimport-file': 'student-import-file',
    'pastearea': 'paste-area',
    'clearstatementmonth': 'clear-statement-month',
    'matchexpensetable': 'match-expense-table',
    'matchexpensecount': 'match-expense-count',
    'matchmonthfilter': 'match-month-filter',
    'labelucretsabahci': 'label-ucret-sabahci',
    'labelucrettamgun': 'label-ucret-tamgun',
    'settingucretsabahci': 'setting-ucret-sabahci',
    'settingucrettamgun': 'setting-ucret-tam-gun',
    'settingucretsabahci2': 'setting-ucret-sabahci-2',
    'settingucrettamgun2': 'setting-ucret-tam-gun-2',
    'settingsnewpass': 'settings-new-pass',
    'settingscurrentpass': 'settings-current-pass'
};

for (const [oldId, newId] of Object.entries(mappings)) {
    c = c.replace(new RegExp(`id="${oldId}"`, 'g'), `id="${newId}"`);
    c = c.replace(new RegExp(`'${oldId}'`, 'g'), `'${newId}'`);
    c = c.replace(new RegExp(`"${oldId}"`, 'g'), `"${newId}"`);
    c = c.replace(new RegExp(`getElementById\\('${oldId}'\\)`, 'g'), `getElementById('${newId}')`);
}

// Bumping version to v=9
c = c.replace(/app.js\?v=\d+/g, 'app.js?v=9');

fs.writeFileSync('public/index.html', c, 'utf8');
console.log('index.html fully synchronized (final sweep).');
