const fs = require('fs');
const c = fs.readFileSync('public/index.html', 'utf8');
const divO = (c.match(/<div/g)||[]).length;
const divC = (c.match(/<\/div>/g)||[]).length;
console.log('div balance:', divO + '/' + divC + ' = ' + (divO===divC?'OK':'MISMATCH'));
console.log('data-page attrs:', (c.match(/data-page=/g)||[]).length);
console.log('app.js?v=4 present:', c.includes('app.js?v=4'));
console.log('page-ogrenci-detay present:', c.includes('page-ogrenci-detay'));
const badClose = c.split('onclick="closeModal').length - 1;
console.log('closeModal without app.:', badClose);
